### PR TITLE
Add pypi badge and installation instructions.

### PR DESCRIPTION
**Pull request by mehdisadeghi**
@carocad Try installing from pypi: `pip install osmtogtfs`

### CODE REVIEW

**Comment by carocad** [comment]
I am not sure if this is an Ubuntu thing but I have to use pip3 instead of just pip since pip is reserved for python 2. 

There seems to be a problem running it directly from the terminal. When I tried the commands just like you wrote them and then tried to run osmtogtfs in the terminal I got en error saying "osmtogtfs command not found" even though the installation says that it succeded. Should I install it as sudo?

**Comment by carocad** [comment]
it seems to have installed correctly now but I get an error when I execute in the terminal

```
Traceback (most recent call last):
  File "/usr/local/bin/osmtogtfs", line 7, in <module>
    from osmtogtfs import cli
  File "/usr/local/bin/osmtogtfs.py", line 4, in <module>
    __import__('pkg_resources').run_script('osmtogtfs==0.1.1', 'osmtogtfs.py')
  File "/home/carocad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/carocad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/osmtogtfs.py' not found in metadata at '/usr/local/lib/python3.6/dist-packages/osmtogtfs-0.1.1.dist-info'
```

**Comment by mehdisadeghi** [comment]
> I am not sure if this is an Ubuntu thing but I have to use pip3 instead of just pip since pip is reserved for python 2.

I think it is related to python2 being the default python on your ubuntu installation. Perhaps I should update the docs and use `python3` and `pip3` to reflect the fact that it is with python3.

> Should I install it as sudo?

sudo is not required. However, pip by default will try to install to system folders. You can mitigate this in two ways:

1. append `--user` to your command: ```pip3 install --user -r requirements.txt```
2. install everything in a virtualenv

P.S. This is an older version, after merging #21 I will release a new version.

**Comment by carocad** [comment]
@mehdisadeghi ok then let me know when the latest version is released and I will try again ;)

**Comment by mehdisadeghi** [comment]
@carocad I published version `v0.1.2`. Let me know whether it improves the situation.

**Comment by carocad** [comment]
@mehdisadeghi still not working :(

it does work if I manually do `python3 osmtogtfs.py`. But it doesnt display any options. If I try to run it with `--help` then it throws an exception.

```
carocad@carocad-Studio-1458:~/Proyectos/osmtogtfs$ python3 osmtogtfs.py --help
Traceback (most recent call last):
  File "osmtogtfs.py", line 20, in <module>
    h.apply_file(sys.argv[1], locations=True, idx='sparse_mem_array')
RuntimeError: Could not detect file format for filename '--help'.
```

Even after upgrading with pip it still throwed an error
```
carocad@carocad-Studio-1458:~/Proyectos/osmtogtfs$ osmtogtfs
Traceback (most recent call last):
  File "/usr/local/bin/osmtogtfs", line 7, in <module>
    from osmtogtfs import cli
  File "/usr/local/bin/osmtogtfs.py", line 4, in <module>
    __import__('pkg_resources').run_script('osmtogtfs==0.1.1', 'osmtogtfs.py')
  File "/home/carocad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/carocad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/carocad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (osmtogtfs 0.1.2 (/home/carocad/.local/lib/python3.6/site-packages), Requirement.parse('osmtogtfs==0.1.1'))
```

**Comment by mehdisadeghi** [comment]
@carocad this is weird. Although I had some problems in that version and then pushed another `0.1.3`. Perhaps you could give it a try?

**Comment by mehdisadeghi** [comment]
> Even after upgrading with pip it still throwed an error

In the log I can see there is `osmtogtfs==0.1.1` which is plain wrong. I think some files are left there from previous installs and are causing problems.

**Comment by mehdisadeghi** [comment]
I tried installing things in a fresh ubuntu and it worked with `pip3 install osmtogtfs` (after installing python3-pyosmium python3-pip of course).

**Comment by carocad** [comment]
It may be because I had previously manually installed with `python3 setup.py install`. So maybe there are some conflicting files there ? I will try today evening

> In the log I can see there is osmtogtfs==0.1.1 which is plain wrong. I think some files are left there from previous installs and are causing problems.

**Comment by mehdisadeghi** [comment]
@carocad I made some refactoring and fixed the setup.py file to cover files that were initially missing from it and released another version, `0.1.4`. Try it (from source or pip) and let me know the result. 
(btw, on my system deleting the old files also helped with fixing some errors, however these are dev problems)

**Comment by mehdisadeghi** [comment]
@carocad we'll open new PRs if something is broken, don't worry! :)

**Pull request merged**
