### PR TITLE
Capture build errors and add them to the output feed.

### LINKED ISSUE #89: Make sure the input OSM data is consistent.
Currently if the input OSM file lacks some relation nodes/ways we won't know it at all. We need to add the functionality to capture those cases. Consider a relation that references many nodes as stops but those nodes are not present in the OSM data. We have to add proper warnings and if necessary add a log file the produced feed.

### PR DESCRIPTION
**Pull request by mehdisadeghi**
closes #89

### CODE REVIEW

**Comment by carocad** [comment]
@mehdisadeghi could you update the gtfs result feeds to see how does this code affect it?

**Comment by mehdisadeghi** [comment]
@carocad there is an extra change in shapes.txt. The reason is, previously I had collected all the member ids and used them to build a shape, no I only collect members that are nodes and pass them to build shape of the road. We ignore ways and super-relations at the moment, which we should fix.

**Comment by carocad** [comment]
@mehdisadeghi are ways suppose to represent the path of the route or is it rather about the platform shape?

**Comment by mehdisadeghi** [comment]
@carocad ways can represent many things, in this case they represent path of the route (when they appear in a relation). So currently we take the nodes of a relation (including stop nodes) which gives us an approximation of the transport route. If we include ways (which we should) it represents a way more accurate picture of the way. The only problem that we had was the size of shapes.txt: https://github.com/hiposfer/osmtogtfs/blob/master/osmtogtfs/osm/builders/shape_builder.py#L31

**Pull request merged**
