### PR TITLE
Feature/agency timezone

### PR DESCRIPTION
**Pull request by mehdisadeghi**
Adds agency_timezone and some other improvements:

- No more `None-to-None` as route long name
- Ignore deleted relations
- Searches ways as well as nodes in order to find a timezone for a relation

You will notice that the number of agencies are way smaller than previous script, the reason is ignoring non-transport routes for finding agencies.

### CODE REVIEW

**Comment by carocad** [comment]
> No more None-to-None as route long name

What would be used now?

> Ignore deleted relations

what do you mean by this? Is this about the cross-border thing?

**Comment by mehdisadeghi** [comment]
> What would be used now?

Nothing. Long names are optional when the short name is provided.


> what do you mean by this? Is this about the cross-border issue?

OSM files contain historical data which are sometimes tagged `deleted`. We don't need them.

**Comment by carocad** [comment]
@mehdisadeghi I just ran the script. Quick questions
- what is the purpose of the random characters in the filename? 
- doesnt that make it more complicate to use in an automatic way? lets say run the script programatically, get the output file and store it in firebase/aws?

**Comment by mehdisadeghi** [comment]
> what is the purpose of the random characters in the filename?

I have not yet any option to accept the filename as an input parameter and I wanted to make sure that every time that I run the program I get a new file and won't get an error that the same file already exists. So this was for my own convenience to be changed later.

> doesnt that make it more complicate to use in an automatic way? lets say run the script programatically, get the output file and store it in firebase/aws?

This makes sense. My initial idea was to write the zip file to standard output when no file name was provided. However I ran into some issues writing a zip file so I decided to just write it in a file and improve it later. There is a limitation here, at the moment I can only write the zip file into a real file on disk and not in a stream (unless I use an external library to write zip files to streams).

**Comment by carocad** [comment]
>  There is a limitation here, at the moment I can only write the zip file into a real file on disk and not in a stream (unless I use an external library to write zip files to streams).

I see. For the time being I am ok with living with that limitation. For the future I guess that providing creating a stream that can be passed upwards would be ideal (thinking of a AWS lambda function or similar)

**Pull request merged**
